// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzXQUc-YN4nvMNk-gmMQPMOPY2j_4Juj4',
    appId: '1:731684064184:android:d7ef74052e5c99e1e9dd4d',
    messagingSenderId: '731684064184',
    projectId: 'operations-hub-73660',
    storageBucket: 'operations-hub-73660.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBecsofQa7tpgYUQlTzq9Arkt5Kua0IDB8',
    appId: '1:731684064184:ios:9b79e1e495ec9445e9dd4d',
    messagingSenderId: '731684064184',
    projectId: 'operations-hub-73660',
    storageBucket: 'operations-hub-73660.firebasestorage.app',
    iosBundleId: 'com.example.operationsHub',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzXQUc-YN4nvMNk-gmMQPMOPY2j_4Juj4',
    appId: '1:731684064184:web:c3783246c7b4cb2ae9dd4d',
    messagingSenderId: '731684064184',
    projectId: 'operations-hub-73660',
    authDomain: 'operations-hub-73660.firebaseapp.com',
    storageBucket: 'operations-hub-73660.firebasestorage.app',
  );
}
